pipeline:
  name: Build harnesspoc
  identifier: Build_himahussain_harnesspoc_1732774980875
  projectIdentifier: HarnessPOC
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Deployment
        identifier: Deployment
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Action
                  name: Application Deployment
                  identifier: Application_Deployment
                  spec:
                    uses: himahussain/harnesspoc
                    with:
                      with: python-app.yml
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Timeout
                        action:
                          type: ManualIntervention
                          spec:
                            timeout: 5s
                            onTimeout:
                              action:
                                type: MarkAsFailure
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: himahussain/harnesspoc
        build: <+input>
