pipeline:
  name: Build harnesspoc
  identifier: Build_himahussain_harnesspoc_1732774980875
  projectIdentifier: HarnessPOC
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Deployment
        identifier: Deployment
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Deploy application
                  identifier: Deploy_application
                  spec:
                    shell: Sh
                    command: |-
                      #!/bin/bash

                      # Variables
                      GITHUB_TOKEN=<+secrets.getValue("pocrepoaccess")>
                      OWNER="himahussain"
                      REPO="harnesspoc"
                      WORKFLOW_FILE="python-app.yml" # Replace with your actual workflow file name
                      REF="main" # Replace with the branch or tag you want to trigger

                      # GitHub API URL to trigger the workflow_dispatch event
                      API_URL="https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE/dispatches"

                      # JSON payload to specify the ref (branch or tag)
                      PAYLOAD="{\"ref\":\"$REF\"}"

                      # Make the API request to trigger the workflow
                      $GITHUB_TOKEN" 
                      curl -L \
                        -X POST \
                        -H "Accept: application/vnd.github+json" \
                        -H "Authorization: Bearer $GITHUB_TOKEN" \
                        -H "X-GitHub-Api-Version: 2022-11-28" \
                        $API_URL \
                        -d '{"ref":"main"}'
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: himahussain/harnesspoc
        build: <+input>
