pipeline:
  name: Build harnesspoc
  identifier: Build_himahussain_harnesspoc_1732774980875
  projectIdentifier: HarnessPOC
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
    - stage:
        name: Onboarding
        identifier: Onboarding
        description: ""
        type: IDP
        spec:
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: CreateCatalog
                  name: CreateCatalog_1
                  identifier: CreateCatalog_1
                  spec:
                    fileName: POC catalog
                    fileContent: |-
                      apiVersion: backstage.io/v1alpha1
                      kind: Component
                      metadata:
                        name: <+pipeline.vars.project_name>
                        description: <+pipeline.vars.description>
                        annotations:
                          backstage.io/techdocs-ref: dir:.
                      spec:
                        type: service
                        owner: <+pipeline.vars.owners>
                        lifecycle: experimental
              - step:
                  type: CreateRepo
                  name: CreateRepo_1
                  identifier: CreateRepo_1
                  spec:
                    connectorType: Github
                    connectorRef: Guthubtestconnector
                    organization: himahussain
                    repository: POCaddition
                    repoType: public
                    description: This is the default repo created as part of POC
                    defaultBranch: main
                    personalAccount: true
              - step:
                  type: RegisterCatalog
                  name: RegisterCatalog_1
                  identifier: RegisterCatalog_1
                  spec:
                    repository: harnesspoc
                    filePath: catalog/
                    branch: main
                    harnessCodeRepoType: account
                  failureStrategies:
                    - onFailure:
                        errors:
                          - Timeout
                        action:
                          type: ManualIntervention
                          spec:
                            onTimeout:
                              action:
                                type: Ignore
                            timeout: 5s
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: himahussain/harnesspoc
        build: <+input>
