name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the application
      run: |
        FLASK_APP=app.py FLASK_ENV=development flask run &
        sleep 5
        curl http://localhost:5000/
        kill $!

    # Add additional steps for deployment here
    # - name: Deploy to Azure Web App
    #   run: |
    #     # Add your deployment commands here
